using System;
using System.Runtime.Serialization;

namespace ActivityContext.Data
{
    /// <summary>
    /// Data object representing single activity.
    /// </summary>
    [DataContract(Name = ElementName, Namespace = ElementNamespace)]
    public sealed class ActivityInfo
    {
        /// <summary>
        /// Name of the XML element generated by <see cref="DataContractSerializer"/>.
        /// </summary>
        public const string ElementName = "Activity";

        /// <summary>
        /// Namespace of the XML element generated by <see cref="DataContractSerializer"/>.
        /// </summary>
        public const string ElementNamespace = Strings.ActivityContextNamespace;

        /// <summary>
        /// Unique ID of the activity.
        /// </summary>
        [DataMember(Order = 0)]
        public Guid Id { get; set; }

        /// <summary>
        /// Name of the activity.
        /// </summary>
        [DataMember(Order = 1)]
        public string Name { get; set; }
    }
}
