using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Runtime.Serialization.Json;

namespace ActivityContext.Serialization
{
    /// <summary>
    /// Data object representing list of activities.
    /// </summary>
    [CollectionDataContract(Name = ElementName, Namespace = ElementNamespace)]
    public sealed class ActivityInfoList : List<ActivityInfo>
    {
        /// <summary>
        /// Name of the XML element generated by <see cref="DataContractSerializer"/>.
        /// </summary>
        public const string ElementName = "Activities";

        /// <summary>
        /// Namespace of the XML element generated by <see cref="DataContractSerializer"/>.
        /// </summary>
        public const string ElementNamespace = Strings.ActivityContextNamespace;

        /// <summary>
        /// Default instance of <see cref="DataContractSerializer"/> for type <see cref="ActivityInfoList"/>.
        /// </summary>
        public static DataContractSerializer DefaultSerializer { get; } = new DataContractSerializer(typeof(ActivityInfoList));

        /// <summary>
        /// Default instance of <see cref="DefaultJsonSerializer"/> for type <see cref="ActivityInfoList"/>.
        /// </summary>
        public static DataContractJsonSerializer DefaultJsonSerializer { get; } = new DataContractJsonSerializer(typeof(ActivityInfoList));
    }
}
